name: BFlow CI pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run code quality
        run: mvn checkstyle:check

      - name: Run tests with coverage JaCoCo - 20% required
        run: mvn clean verify